on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
permissions:
  pull-requests: write
  contents: write
jobs:
    goreadme:
        runs-on: ubuntu-latest
        steps:
        - name: Check out repository
          uses: actions/checkout@v2
        - name: GoDoc Action
          uses: ktr0731/godoc-action@v0.1.0
